name: Development

on:
  workflow_dispatch:
#  push:
#    branches-ignore:
#      - main

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set environment variables
        run: |
          echo "DOCKERHUB_REPO=${{ vars.DOCKERHUB_REPO || 'runpod' }}" >> $GITHUB_ENV
          echo "DOCKERHUB_IMG=${{ vars.DOCKERHUB_IMG || 'worker-v1-vllm' }}" >> $GITHUB_ENV
          echo "HUGGINGFACE_ACCESS_TOKEN=${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${GITHUB_REF##refs/heads/}" | sed 's/\//-/g' >> $GITHUB_ENV

      - name: Build and push the images to Docker Hub
        uses: docker/bake-action@v4
        with:
          push: true
        env:
          DOCKERHUB_REPO: ${{ env.DOCKERHUB_REPO }}
          DOCKERHUB_IMG: ${{ env.DOCKERHUB_IMG }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
          HUGGINGFACE_ACCESS_TOKEN: ${{ env.HUGGINGFACE_ACCESS_TOKEN }}
